stages:
 - deploy
 - trigger-other-builds

pages:
  stage: deploy
  image: schickling/latex
  script:
    - mkdir public
    - pdflatex -output-directory public README.md 
  artifacts:
    paths:
      - public
  only:
     - main

trigger-gshakhn-com:
  stage: trigger-other-builds
  script: 
    - curl -X POST -F token=$GSHAKHN_TOKEN -F ref=main https://gitlab.com/api/v3/projects/$GSHAKHN_PROJECT_ID/trigger/builds
